### ISSUE TITLE
Parameter format is not needed in CompositeC1Contrib.Localization.TFormat()

### ISSUE THREAD

**Issue by jimmyrn** [burningice2866/CompositeC1Contrib#1]
https://github.com/burningice2866/CompositeC1Contrib/blob/master/Localization/C1Res.cs#L32

The parameter "format" is not used, at should be removed.

**Comment by burningice2866** [comment]
Good catch! Will be removed asap.

**Comment by burningice2866** [comment]
Fixed in https://github.com/burningice2866/CompositeC1Contrib/commit/19e754f1e0cf4cb7913289a34295d70c136aaca8
