### ISSUE TITLE
'0 0 0 ? * * 2016' is an invalid crontab expression

### ISSUE THREAD

**Issue by aeont** [burningice2866/CompositeC1Contrib#4]
'0 0 0 ? * * 2016' is an invalid crontab expression. It must contain 5 components of a schedule in the sequence of minutes, hours, days, months, and days of week.
According to this: https://www.freeformatter.com/cron-expression-generator-quartz.html should work... 

..and thank you for great package!

**Comment by burningice2866** [comment]
@aeont your example isn't a valid pure cron expression. You're link is describing quartz cron expressions which is their own custom extensions to cron. You need to use something like https://crontab.guru or http://cron.schlitt.info/ to validate your cron expression.

**Comment by aeont** [comment]
thank you

**Comment by burningice2866** [comment]
Hangfire is in the process of writing a new library to handle cron parsing named [Cronos](https://github.com/HangfireIO/Cronos). One suggestion there is to support a year-component, but its kinda Up-For-Grabs if someone wants to code it.

https://github.com/HangfireIO/Cronos/issues/3
