### ISSUE TITLE
Error on same key in multiple sites

### ISSUE THREAD

**Issue by MoeCphcloud** [burningice2866/CompositeC1Contrib#5]
https://github.com/burningice2866/CompositeC1Contrib/blob/6b4fdbb23a7ca8d716de334712fa8a242b5fff6c/Localization/C1Console/WorkFlows/AddResourceWorkflow.cs#L53

If there is multiple sites and you want to add the same key to each site you get an error, since the check is on the key and not the key + site combination.

**Comment by burningice2866** [comment]
Thank you for reporting. Fixed in commit 86536f648a83e57033158f42c39389a58aa50d70
